### ISSUE TITLE
Language file error <nuNPCDestinations - Animations)

### ISSUE THREAD

**Issue by HyperDioxide** [Nutty101/NPC_Destinations2#11]
Hello!
I have encountered a bug:
Minecraft version: 1.12.2
Citizens: citizens-2.0.22-SNAPSHOT
nuNPCDestinations:  2_1_20
nuNPCDestinations - Animations: 2_6
I cannot use any of the functions made available with the animation addon.
![inked2018-02-17_21 48 58_li](https://user-images.githubusercontent.com/19249764/36345566-50c14550-142d-11e8-98b8-1c32bc00fce6.jpg)
![image](https://user-images.githubusercontent.com/19249764/36345568-55670630-142d-11e8-9226-6697c7d0c206.png)
In your picture here, you can see the animations wave icon.
for me it is just blank []
![inked2018-02-17_21 57 02_li](https://user-images.githubusercontent.com/19249764/36345575-a6f7f8b0-142d-11e8-88e1-0e3e3e3ea83a.jpg)
Is there any solution for this?
Here is my en_def_animations.yml file
https://pastebin.com/Y5wJwZaD
Thank you  in advance!

**Comment by Nutty101** [comment]
I need to clean up my load orders. If you just installed that plugin. You need to restart the server again before it shows up.
