### ISSUE TITLE
NPC Not Moving In-between Locations: Animation Addon

### ISSUE THREAD

**Issue by doitliketyler** [Nutty101/NPC_Destinations2#12]
Hey there. I'm having a heck of a time trying to get these NPCs to go to their locations. I have 1 NPC setup that is also a "Shopkeeper" and has 2 locations, one at sunrise and one at sunset. I also have animations activated for it so at sunset, they will go to sleep.

Now when the time changes at either sunrise or sunset they don't change locations. Do you have any idea what would be causing this? Do you think its Shopkeepers interfering?

**Comment by Nutty101** [comment]
Select the NPC, and type _/nd debug_  that should give some info as to why it cannot move.

**Comment by Wqrld** [comment]
i dont think this is shopkeepers, i remember having this problem too with npcs not standing up when they start walking and that bugs them out

**Comment by Nutty101** [comment]
Is this still an issue?

**Comment by doitliketyler** [comment]
Definitely, if they are shopkeepers. I setup non-shopkeeper NPCs on another server that worked fine.

**Comment by Nutty101** [comment]
Would you be on discord? If so can you chat me on there?

**Comment by Nutty101** [comment]
https://discord.gg/jE5fVRZ

**Comment by doitliketyler** [comment]
Yep

**Comment by Nutty101** [comment]
Oh man, I should have looked at your name. Haha, slap me.

**Comment by Nutty101** [comment]
Old issue that was resolved at some point.
