### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by Wqrld** [Nutty101/NPC_Destinations2#13]
can you enable the wiki feature on github so people like me can make/read a written documentation instead of just videos

**Comment by Nutty101** [comment]
Yeah, that means a ton of time spent on doing it. As much as I want to, I lack time. Would be good though. Leaving this open for discussion.

**Comment by Wqrld** [comment]
atleast enable it so i can write down a bit of what i know :)

**Comment by Nutty101** [comment]
I'll get a table setup tonight
