### ISSUE TITLE
Doors (Metal & Wood) cause NPC to Teleport after opening the door.....

### ISSUE THREAD

**Issue by Jawakotb** [Nutty101/NPC_Destinations2#2]
Nutty,
Trying to ENTER a building:  The NPC goes up to the door (metal or wood) opens the door, then walks past the opening, closes the door, then walks east and then south then west trying to get access to the building spot I set. 

Trying to EXIT a building: The NPC walks up and opens the door, then walks east for 2 blocks, closes the door then teleports to the location I set outside of the building.

NPC is a normal NPC (not an animal)  Player is equipped with a fishing rod. (But he does the same with or without the fishing rod.  (he was renamed "Fisherman Bob" based on the player 'HillBilly' skin.)

I have tried this with 1 wide and two wide doors, both metal and wood.     .....and I did grant perms to open both when testing.  ;)

GOOD NEWS:   If I put in Gates, he has NO ISSUES entering or exiting the building. 
BAD NEWS: This is a two wide opening. He does the same as doors if this is only one wide.  

Thanks Nutty

**Comment by Jawakotb** [comment]
UPDATE:  He now --after a few day cycles-- can enter the building with a one wide GATE, but he cannot exit.  He opens the gate, does a spin, closes the gate.... stops for a second, spins then teleports

**Comment by Jawakotb** [comment]
Could the door closing step be occurring too soon, messing up the pathfinding?

**Comment by Nutty101** [comment]
It's an issue with the old pathfinder in citizens.  Use the new one.

  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: **true**

**Comment by Nutty101** [comment]
Defaulted the NPCs to use the new pathfinder from citizens for now. So going to close this one. Not sure that they are going to fix the doors on the pathfinder.

**Comment by Jawakotb** [comment]
Thanks Nutty.   (Except Pathfinding section was in config.yml not saves.yml)

Edited 'use-new-finder" to TRUE.   Will test and let you know how I make out.

**Comment by Jawakotb** [comment]
welp... had to revert back to FALSE as all NPCs are simply walking in circles now.

**Comment by Nutty101** [comment]
Gurrr

**Comment by Nutty101** [comment]
I think I need to make my own pathfinder on this one.  I have been trying to work around it but so far the path finding has been an issue even with the old and new one.

**Comment by Nutty101** [comment]
Old, so closing. new release will get this resolved.
