### ISSUE TITLE
Debug doesn't restore block properly when 2 slabs

### ISSUE THREAD

**Issue by bundabrg** [Nutty101/NPC_Destinations2#21]
When debug is enabled and a path is shown with the red blocks, when the red blocks are removed holes are left.

This only seems to happen when 2 slabs are piled up on top of each other and look like a single block. For example I've got 2 stone slabs on the floor (for some reason) and after the blocks are restored I have what looks like a line of holes.

Example: https://imgur.com/a/x7gq97c

They're not really missing. If I reload or click them, then they appear.

**Comment by Nutty101** [comment]
Yeah, I just send packets to the client to make that debug path. I will see what I can come up with for it. Just be a few, i'm swamped :(

**Comment by bundabrg** [comment]
No problems, I'm impressed with everything so far. I'm actually going to see if I can compile this and submit a PR for this issue. Just raising the issue so we have a trail.

**Comment by bundabrg** [comment]
Ok I'm going to have to admit defeat. I can't work out how to compile this whilst respecting all the different API's, without totally pulling everything apart into separate maven modules and shading them together at the end. Tell me your secret :)

**Comment by Nutty101** [comment]
Sadly, it's not a maven project. I've thought about converting it, but like with all things of late. A lack of time.

The lines that are the issue, least should be.   
[CitizensProcessing:513](https://github.com/Nutty101/NPC_Destinations2/blob/de18e28b8bd5acb8deda116045e93d509ad239b6/src/net/livecar/nuttyworks/npc_destinations/citizens/Citizens_Processing.java#L513)   
and   
[CitizensProcessing:528](https://github.com/Nutty101/NPC_Destinations2/blob/de18e28b8bd5acb8deda116045e93d509ad239b6/src/net/livecar/nuttyworks/npc_destinations/citizens/Citizens_Processing.java#L528)

**Comment by bundabrg** [comment]
Ok, I managed to compile it. I had to set it up for Maven though but I hope I can pull my changes back to your form for anything I do. If you're interested in the mavenized version you can find it at: https://github.com/bundabrg/NPC_Destinations2/tree/feature/maven   (I can provide a PR if you like but I'm not confident about my maven skills ;-)

I'll take a check about fixing this issue which I'm sure should be easy and then work on what I actually did that work for.

**Comment by bundabrg** [comment]
Tested with 1.13 PaperMC and 1.12.2 PaperMC, which use alternative methods.

**Comment by Nutty101** [comment]
Changed a bit on this, it should be ok with how it is doing it. The issue now lies in 1.13 and how it manages linked tiles. That one is becoming a bit of a pain. Going to close this as the general function is resolved, but there is a lingering issue with connected tiles.
