### ISSUE TITLE
LightAPI doesn't seem to work

### ISSUE THREAD

**Issue by derPiepmatz** [Nutty101/NPC_Destinations2#27]
On startup the console shows this:
```
[20:52:42] [Server thread/INFO]: [NPC_Destinations] LightAPI (V3.2.7) found, adding support for NPC torch lighting.
```
But still if I equip an npc with a torch no light will show up. Maybe I did something wrong or it just doesn't work.

**Comment by Nutty101** [comment]
Looking into it.

**Comment by Nutty101** [comment]
What version of MC are you on?

**Comment by derPiepmatz** [comment]
I'm running my minecraft on 1.12.2 on `CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by Nutty101** [comment]
I have been toying with this one and it works on 1.12 > 1.13.2 without fail. Does the NPC have more than 1 location? And if you use /nd goloc # to swap between them does it light up after making it to the next one?

**Comment by derPiepmatz** [comment]
I'm not quite sure, need to test it later but it seems that npcs who wander can't emit light. Am i right?

**Comment by Nutty101** [comment]
Yeah, seems it does not in wandering mode unless they are already lit up. I need to move some parts in the code around to ensure the lighting is still being updated. I will try to get a fix for this into the next release.

**Comment by Nutty101** [comment]
Resolved for you.  See the link below for a fixed copy.
https://github.com/Nutty101/NPC_Destinations2/releases/tag/2.3.6
