### ISSUE TITLE
WorldGuard & NMPCDest Bug

### ISSUE THREAD

**Issue by Midnight9746** [Nutty101/NPC_Destinations2#32]
NPC Destinations cannot pass ChunkUnload Event, and is seeming to unload NPCS https://pastebin.com/eT9GFh2B

> Original report https://pastebin.com/2VdfFHk8

**Comment by Nutty101** [comment]
Cool :)  Thanks for adding though. Be nice to know if others are using it that it may be related.

**Comment by Midnight9746** [comment]
@Nutty101 I feel stupid lol, the citizens despawning and that error is caused by me making ClearLag unload chunks every 5 minutes. Thus it was fixed, although the only other issue now is the Farmer plugin throwing errors, after '/npcdest --npc 66 locfarmer 0' like I don't have to type anything and it throws an internal error, Unsure if config files are outdated or what though,

**Comment by Nutty101** [comment]
I got another error posted #33  that may be the same as this. Looking at it.
