### ISSUE TITLE
WE/WG Bug in WE: 7.0.0-beta-05 and WG: 7.0.0-beta-03

### ISSUE THREAD

**Issue by Rincewind34** [Nutty101/NPC_Destinations2#33]
Hey there,
I'm running the news builds of WorldGuard and WorldEdit on my server resulting in the following exception: https://pastebin.com/1yAVq6VY

Would be nice, if you could fix that ;)

**Comment by Nutty101** [comment]
Will look into it.

**Comment by Rincewind34** [comment]
Great. It is actually a simple fix. I was able to do this myself. Its just in in WG7.0.0 module the usage of WorldGuardPlatform.getWorldByName. You can bypass that call by using BukkitAdapter.adapt(world) and use WorldGuard.getInstance().getPlatform().getRegionContainer().get(BukkitAdapter....);

**Comment by Nutty101** [comment]
Yeah, I've been trying to keep both the old 7.0 and new api working. So it may be related. I'll check it out.

**Comment by Midnight9746** [comment]
@Nutty101 They are related, I'm using those same versions.

**Comment by Drc-DEV** [comment]
Please can you fix this? I can't update wg/we in my server because NPC-Destinations is not working with wg 7-beta3. All the other plugins already updated...
