### ISSUE TITLE
Betonquest 2.0

### ISSUE THREAD

**Issue by Passeo** [Nutty101/NPC_Destinations2#54]
So Did you guys know theres betonquest 2.0 ? . Please add betonquest 2.0 for npc destination
https://pastebin.com/pJeS1Rpt

And please add feature that when fire the goto events, it have done instruction so when npc arrive to the location it will run some events
you guys can see the example in here https://docs.betonquest.org/RELEASE/User-Documentation/Compatibility/#move-npc-movenpc

but betonquest movenpc events is something buggy so I hope npc destination will update to betonquest 2.0

**Comment by Nutty101** [comment]
Yeah, someone else actually did update it to support that version. I need to update my branch though. On the NPC movement, they use the native method that I use in Citizens. It's when the NPC has move more than say 15 blocks that it can get messy as Citizens does not really manage long distances on that method.  Are you looking for Short distances or longer distances?

**Comment by FruitToast** [comment]
I just looking for short distance. But npc will move to a different position (but it still short distance), Sadly betonquest cant handle that and the npc just stay in one place and still fire the events

**Comment by Nutty101** [comment]
This has been done, snag the latest update and it should do what you are looking for.
