### ISSUE TITLE
Lang file?

### ISSUE THREAD

**Issue by QueenKisaki** [Nutty101/NPC_Destinations2#7]
Not sure what this means, I just installed destinations and the farmer addon. The file is there though, do I need to change anything in it?

21.06 15:29:33 [Server] INFO Missing language [en_def-farmer.messages.plugin_description] check your language files.

**Comment by QueenKisaki** [comment]
I downgraded to farmer addon 2.0 and the error is not there. Maybe because I use 1.11.2 and not 1.12?

**Comment by QueenKisaki** [comment]
well updated back to 2.2 and that error is gone but my npc just spins in circles on farmland. ill try to mess around and see why. would really be great if you had a video tutorial on how to set up farming. commands are easy but seeing how its supposed to work would help lol. thanks for great plugins! :)

**Comment by Nutty101** [comment]
The NPC spinning is due to this ([Citizens Issue 1171](https://github.com/CitizensDev/Citizens2/issues/1171). I do have an update coming out that will address this issue as well as a couple other items. It's in the works.  For now, you can use **/nd citizens 0.5 0.5 N Y Y Y**  to  get them working.

Not sure on that missing language error. I am trying to support 1.8.8 > Current with my plugins. So versions shouldn't matter. if they do, I will get it fixed.

**Comment by QueenKisaki** [comment]
What does it mean when it says an npc is traveling but they haven't moved at all? I made another one to fish but this one just stands there lol

**Comment by Nutty101** [comment]
Check that you used /nd autoset  to make sure they can move.  Will check out the rest of the stuff soon, just been slammed with work and life. :(   Will figure it out though.

**Comment by QueenKisaki** [comment]
Yes I used /nd autoset and they need to be restarted just about everyday. There is only 1 npc that never has issues though so I'll just keep playing around with them. I understand how busy life is lol no worries. Thanks for all you do :)

**Comment by Nutty101** [comment]
The farmer shouldn't use the wandering. The farmer plugin does that for you. Can you paste me your config for that NPC?

**Comment by QueenKisaki** [comment]
https://pastebin.com/S1jjyanE

didn't know it saved in the citizens file lol. I see that when I've made changes to him that its still there. I'll try to clean that up. Right now I have wandering off but I end up having to restart them int he morning when they wake up, the farmer doesn't sleep but he'll stay at his night spot in the am too.

**Comment by QueenKisaki** [comment]
This probably has nothing to do with npcdest but I keep getting:
24.06 11:41:16 [Server] INFO Quester not found for UUID "52ce8106-3cd6-24af-a79c-da886b6f34a8". Consider adding them to the Quester blacklist.
Since he updated the quests plugin, but, I never had any quests on the hunter trainer yet since he was set up properly. It seems that the saves file is also not right because I removed all the door opening stuff from this guy but it says on the file he's allowed to. 
They seemed to get stuck on just standing there opening and closing doors so I just removed all doors and the perms to open them.

**Comment by QueenKisaki** [comment]
Ugh so sorry, I just removed all the naughty npcs and remade them and now they're working.

**Comment by Nutty101** [comment]
Missed that you updated this with more information.

The being stuck at doors alot of times is based on the old pathfinder. So using /nd citizens 1 1 N N N  will break the doors. Been working on a work around as i have not seen a fix in Citizens and i get nailed with this issue all day long.
